### ISSUE TITLE
Little Typo

### ISSUE THREAD

**Issue by something-strange-to-eat** [RainerChiang/simpleness#3]
Hello there,

thank you for the theme! There is a little typo in the install command:

```
cp themes/simepleness/exampleSite/config.toml .
```

simepleness should be simpleness

Best regards!

**Comment by RainerChiang** [comment]
@something-strange-to-eat thanks for checking, the typo has fixed, [1b558bb](https://github.com/RainerChiang/simpleness/commit/1b558bbd00aede034c812b2c26d9feaa099100e9).
