### ISSUE TITLE
Table of content support

### ISSUE THREAD

**Issue by leiless** [RainerChiang/simpleness#5]
From https://rainerchiang.github.io/posts/2020-09-22-hello-hugo/, I can tell that **Table of content** is available in this `simpleness` theme, however, when I switch to this theme, I see no TOC in my Hugo site. :-(

![image](https://user-images.githubusercontent.com/38041294/130098477-fcd9e7f3-6119-495c-aae9-f5ffaf700da3.png)

Is there anything wrong since the main repo README.md with **Table of content** feature unchecked?

**Comment by leiless** [comment]
https://rainerchiang.github.io/simpleness/posts/post-5/
https://github.com/RainerChiang/upload-theme/blob/main/content/posts/post-5.md
https://raw.githubusercontent.com/RainerChiang/upload-theme/main/content/posts/post-5.md

OK, I must set `toc: true` so I can use it.
However, I can tell that TOC is only applicable for `h2` and `h3`, which `h1` is not available.
We may reveal `h1` in result TOC.

**Comment by brunoamaral** [comment]
In the full context of the HTML page, should H1 be considered in the TOC ? It usually marks the main title of the page and there should be only 1 to comply with web standards. Everything inside the content file should start at H2 as not to break the sequence of headings.

**Comment by leiless** [comment]
OK, thanks! I know nothing about web standards previously.
